apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-keeper-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: notes-keeper
  template:
    metadata:
      labels:
        app: notes-keeper
    spec:
      containers:
        - name: notes-keeper
          image: yash5090/notes-keeper:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
